---
general:
  cpiApiServiceKeyCredentialsId: "demo1-apikey"
  integrationFlowId: "Get_Product_Details_API"
stages:
  uploadStage:
    enabled: true
  deployStage:
    enabled: true
  integrationTestStage:
    enabled: false
steps:
  integrationArtifactUpload:
    packageId: "INT_SUITE_EMPOWERMENT_DEMOS"
    integrationFlowName: "Get Product Details API"
  integrationArtifactTriggerIntegrationTest:
    contentType: ""
    messageBodyPath: ""
    integrationFlowServiceKeyCredentialsId: ""
